### ISSUE TITLE
Decouple user model into separate classes

### ISSUE THREAD

**Issue by samtay** [MikeTayC/apprentice.dev#1]
As discussed, methods that don't have to do with any specific model should get moved into a `Core_Model_Abstract` class, which extends `Core_Model_Object`. For example, 

`App_Model_User::getCount()`  :arrow_forward:   `Core_Model_Abstract::getCount()`

Similarly, methods that have nothing to do with user but only other tables, should be moved into their own model class. For example,

`App_Model_User::getAllTagsFromTagTable()`  :arrow_forward:   `App_Model_Tag::getAll()`

`App_Model_User::getAllLessonNames()` :arrow_forward:   `App_Model_Lesson::getAllNames()`

**Comment by samtay** [comment]
Looks like this issue is ok now? Close out if you want

**Comment by MikeTayC** [comment]
yeah for the most part
